### ISSUE TITLE
Issue when i use model to translate from English to Vietnamese

### ISSUE THREAD

**Issue by duynvher** [vietai/SAT#9]
When i use model to translate Eng-Vie, the model has converted units like pounds, feet, to kilograms, meter. But i don't want to convert those units. How can I use the model without converting those units?

**Comment by heraclex12** [comment]
Hi @Nduy2k 

I guess our model is trained on the parallel data (En-Vi) in which pounds, feet, and kilograms are translated into the target language. It's hard to re-train the model so that it doesn't translate those units, so I think a possible solution for your case is to use rule-based approaches (i.g., regex) to fix that. Maybe you could try to mask those units before throwing them into our model.
